### PR TITLE
Added verbose option

### PR DESCRIPTION
**Pull request by ivallesp**
I added an option to control the "verbosity". For this, I added the parameter "verbose" in the __init__ method of the __init__.py file and to the train function in the trainers.py file. In addition, I passed this argument to the "self._trainer.train()" call in the __init__ file and added a condition to make the prints in the trainer.py file.

### CODE REVIEW

**Comment by ivallesp** [comment]
I signed it!

**Comment by ivallesp** [comment]
I updated it!

**Comment by ivallesp** [comment]
I signed it!

**Comment by ivallesp** [comment]
Well, I signed the CLA and I checked that I signed it with the same e-mail address which I used to perform the commits, what's wrong?

**Comment by terrytangyuan** [comment]
Perhaps check to see if that email address is your Github primary email?

**Comment by ivallesp** [comment]
Thanks for replying. Yes, that's what I checked, my GitHub account main address is the one I registered in the CLA website!

**Comment by ivallesp** [comment]
What am I doing wrong? how can I correct it?

**Comment by ivallesp** [comment]
Oh I've found that I don't have properly written my email in the .gitconfig file, instead, I have a random string (email=ehsjidkrofirj). Could it be the problem? If so, how can I solve it? Do I have to start from zero committing the files with my config file fixed, pushing and re-sending a push-request? Sorry it's my first contribution.

**Comment by terrytangyuan** [comment]
Follow this link to set up and check your configs, e.g. email, username https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

Then probably a new PR or add new commit and squash them together. (ref: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)

**Comment by ivallesp** [comment]
Thank you, I'm going to try with a new PR.

**Pull request closed without merging**
