### PR TITLE
ENH: Added setup option for training on multiple GPUs

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by ilblackdragon** [comment]
I actually haven't used multi GPU, so question:
  from the example like this - https://github.com/aymericdamien/TensorFlow-Examples/blob/master/multigpu_basics.py it seems that you specify different parts of the graph under different devices and then session doesn't need to be inside the tf.device scope.

So I'm not sure then devices should be passed to fit(), you can use it when defining model like this (pseudo code):

```Python
def attentive_rnn(X, y):
  with tf.device('/gpu:1'):
     encoding = rnn.rnn(X, ...)
 with tf.device('/gpu:2'):
     attention = softmax_over_encoding()     
     return logistic_regression(attention, y)
estimator = Estimator(model_fn=attentive_rnn, ...)
estimator.fit(...)
```

Also TF should automatically assign if you have mutliple GPUs nodes. So we can add some debugging flags to enable "log_device_placement".

What do you think?

**Comment by terrytangyuan** [comment]
Yeah that makes sense. I can also prepare small demo for using multiple GPUs. Should the debugging flag be an option in `_setup_training` when assigning `_session` then?

**Comment by ilblackdragon** [comment]
May be it's better to add parameter to the `__init__` and then use it in the `_setup_training`? 
This will keep `fit` interface similar to the scikit-learn (ideas was to try at least make sure you can replace in your code TFEstimator to some other estimator and will still work).

**Comment by terrytangyuan** [comment]
Sure. I have made the changes and added a demo.

**Comment by ilblackdragon** [comment]
Nice! :+1:

**Pull request merged**
